name: GrenadesPlus
main: team.GrenadesPlus.GrenadesPlus
version: 1.0
depend: [Spout, ApiPlus]
authors: [SirTyler, Atlan1]
description: >
             Grenades+ - Grenades - make creepers go boom!
commands:
    grenades+:
        description: Grenades+ commands.
        aliases: [gren+,grenades]
        usage: /grenades+ help - Displays the Help Menu.             